version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@3.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: back-end install
          command: |
            npm run backend:install
      - run:
          name: back-end build
          command: |
            npm run backend:build
      - run:
          name: back-end test
          command: |
            npm run backend:test
      - run:
          name: back-end deploy
          command: |
            npm run backend:deploy
      - run:
          name: front-end install
          command: |
            npm run frontend:install
      - run:
          name: front-end build
          command: |
            npm run frontend:build
      - run:
          name: front-end test
          command: |
            npm run frontend:test
      - run:
          name: front-end deploy
          command: |
            npm run frontend:deploy
